name: 'Hello'
description: 'Just testing actions, hello world'
author: 'Christian'
inputs:
  name:
    description: 'The name to say hello to'
    default: 'World'
runs:
  using: 'node12'
  main: 'lib/main.js'
